apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  volumeName: mysql-pv
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      release: "stable"

